services:
  db:
    extends:
      file: db/docker-compose.yml
      service: db
    networks:
      - backend
    ports:
      - 5434:5432

  flyway:
    extends:
      file: flyway/docker-compose.yml
      service: flyway
    networks:
      - backend
    depends_on:
      db:
        condition: service_healthy

  app:
    extends:
      file: app/docker-compose.yml
      service: app
    networks:
      - backend
      - prodenv-shared-internal
      - artist-insight-shared
    depends_on:
      flyway:
        condition: service_completed_successfully

  frontend:
    extends:
      file: frontend/docker-compose.yml
      service: frontend
    networks:
      - prodenv-shared-internal
    depends_on:
      app:
        condition: service_healthy

volumes:
  artist-insight-service-volume-db:
  artist-insight-service-volume-db-backup:

networks:
  backend:
  prodenv-shared-internal:
    external: true
  artist-insight-shared:
    external: true