spring:
  jpa:
    hibernate:
      ddl-auto: none
  datasource:
    url: jdbc:h2:file:./h2_db #;AUTO_SERVER=TRUE
    username: sa
    password: sa
    driver-class-name: org.h2.Driver

  flyway:
    enabled: false
    clean-disabled: false
    locations:
      - filesystem:templates/docker/flyway/sql/tables

  sql:
    init:
      mode: always
#      data-locations: classpath:sql/test-data.sql

app:
#  additional-profiles: flyway-clean-migrate