postgres-url: jdbc:postgresql://${POSTGRES_ADDRESS:localhost}:${POSTGRES_PORT:5434}/${POSTGRES_DB:artist_insight_service}

spring:
  datasource:
    url: ${postgres-url}
    username: ${POSTGRES_APP_USER:d}
    password: ${POSTGRES_APP_PASSWORD:d}
  flyway:
    enabled: false