server:
  port: 9016
  servlet:
    session:
      cookie:
        domain: ${SERVER_SERVLET_SESSION_COOKIE_DOMAIN:localhost}
        name: ${SERVER_SERVLET_SESSION_COOKIE_NAME:JSESSIONID-LOCAL}

app:
  minimised-http-servlet-logging: true
  initial-user-gpt-usages: 10
  initial-global-gpt-usages: 50
  csrf-cookie-name: ${CSRF_COOKIE_NAME:XSRF-TOKEN-LOCAL}

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus,metrics
  endpoint:
    health:
      show-details: always
      probes:
        enabled: true
    prometheus:
      enabled: true
  metrics:
    tags:
      application: artist-insight-service
health:
  enabled: true
  external:
    refresh-interval-ms: 60000
    initial-delay-ms: 0

spotify:
  healthcheck-user-id: 3126nx54y24ryqyza3qxcchi4wry