spring:
  security:
    oauth2:
      client:
        registration:
          spotify-artist-insight-service:
            provider: spotify
            client-id: ${SPOTIFY_CLIENT_ID}
            client-secret: ${SPOTIFY_CLIENT_SECRET}
            authorization-grant-type: authorization_code
            scope: user-follow-read, user-read-private
          spotify-client-credentials:
            provider: spotify
            client-id: ${SPOTIFY_CLIENT_ID}
            client-secret: ${SPOTIFY_CLIENT_SECRET}
            authorization-grant-type: client_credentials
            scope: user-follow-read, user-read-private
        provider:
          spotify:
            issuer-uri: https://accounts.spotify.com
            user-info-uri: https://api.spotify.com/v1/me
            userNameAttribute: display_name

app:
  default-success-url: ${DEFAULT_SUCCESS_URL:http://localhost:3000}
  login-url: ${LOGIN_URL:http://localhost:3000/login}

spotify:
  api-base-url: https://api.spotify.com/v1

