spring:
  security:
    oauth2:
      client:
        registration:
          spotify-artist-insight-service:
            provider: spotify
            client-id: 1234e12345678fafbd90fdce7540e12e
            client-secret: 12b123b7c2ea4cf28abc83f3e12345de
            authorization-grant-type: authorization_code
            scope: user-follow-read, user-read-private
          spotify-client-credentials:
            provider: spotify
            client-id: 1234e12345678fafbd90fdce7540e12e
            client-secret: 12b123b7c2ea4cf28abc83f3e12345de
            authorization-grant-type: client_credentials
            scope: user-follow-read, user-read-private
        provider:
          spotify:
            issuer-uri: ${SPOTIFY_STUB_BASE_URL:http://localhost:8100}
            user-info-uri: ${SPOTIFY_STUB_BASE_URL:http://localhost:8100}/v1/me
            userNameAttribute: display_name
  cloud:
    contract:
      stubrunner:
        stubs-mode: CLASSPATH

app:
  default-success-url: ${DEFAULT_SUCCESS_URL:http://localhost:3000}
  login-url: ${LOGIN_URL:http://localhost:3000/login}

spotify:
  api-base-url: http://localhost:8100/v1

stub-spotify-mergeable:
  cloud:
    contract:
      stubrunner:
        ids:
          - org.taonity:spotify-contracts:@project.version@:stubs:8100

logging:
  level:
    WireMock: warn